# Generated by Django 5.2.6 on 2025-09-05 18:29

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=cinema.models.movie_image_upload_path,
            ),
        ),
    ]
